In [44]:
import pandas as pd
import numpy as np
DATASET = pd.read_csv('Comune-di-Milano-Servizi-alla-persona-parrucchieri-estetisti(in).csv',sep=';',encoding='unicode_escape')
DATASET

,Tipo esercizio pa,Ubicazione,Tipo via,Via,Civico,Codice via,ZD,Prevalente,Superficie altri usi,Superficie lavorativa
0,NaN,LGO DEI GELSOMINI N. 10 (z.d. 6),LGO,DEI GELSOMINI,10,5394.0,6,NaN,NaN,55.0
1,NaN,PZA FIDIA N. 3 (z.d. 9),PZA,FIDIA,3,1144.0,9,CENTRO MASSAGGI RILASSANTI NON ESTETICI,2.0,28.0
2,NaN,VIA ADIGE N. 10 (z.d. 5),VIA,ADIGE,10,4216.0,5,CENTRO BENESSERE,2.0,27.0
3,NaN,VIA BARACCHINI FLAVIO N. 9 (z.d. 1),VIA,BARACCHINI FLAVIO,9,356.0,1,TRUCCO SEMIPERMANENTE,NaN,NaN
4,NaN,VIA BERGAMO N. 12 (z.d. 4),VIA,BERGAMO,12,3189.0,4,NaN,NaN,50.0
...,...,...,...,...,...,...,...,...,...,...
3904,TIPO D ESTET.APPAR.ELETTROMECC;TIPO C TRATT.ES...,VIA SARPI FRA' PAOLO N. 1 con ingr.da v.le mon...,VIA,SARPI FRA' PAOLO,1,7210.0,1,NaN,NaN,NaN
3905,TIPO D ESTET.APPAR.ELETTROMECC;TIPO C TRATT.ES...,CSO DI PORTA TICINESE N. 4 ; (z.d. 1),CSO,DI PORTA TICINESE,4,541.0,1,NaN,NaN,65.0
3906,TIPO D ESTET.APPAR.ELETTROMECC;TIPO C TRATT.ES...,VIA CANDOGLIA N. 2 ; (z.d. 9),VIA,CANDOGLIA,2,1518.0,9,NaN,NaN,NaN
3907,TIPO D ESTET.APPAR.ELETTROMECC;TIPO C TRATT.ES...,VIA NIRONE num.002a; (z.d. 1),VIA,NIRONE,NaN,640.0,1,NaN,NaN,NaN
3908,Truccatore,VIA MADONNINA N. 15 ; (z.d. 1),VIA,MADONNINA,15,134.0,1,NaN,NaN,85.0

In [45]:
# Divido la colonna 'Tipo esercizio pa' in più righe
df = DATASET.assign(**{'Tipo esercizio pa': DATASET['Tipo esercizio pa'].str.split(';')}).explode('Tipo esercizio pa')
df

,Tipo esercizio pa,Ubicazione,Tipo via,Via,Civico,Codice via,ZD,Prevalente,Superficie altri usi,Superficie lavorativa
0,NaN,LGO DEI GELSOMINI N. 10 (z.d. 6),LGO,DEI GELSOMINI,10,5394.0,6,NaN,NaN,55.0
1,NaN,PZA FIDIA N. 3 (z.d. 9),PZA,FIDIA,3,1144.0,9,CENTRO MASSAGGI RILASSANTI NON ESTETICI,2.0,28.0
2,NaN,VIA ADIGE N. 10 (z.d. 5),VIA,ADIGE,10,4216.0,5,CENTRO BENESSERE,2.0,27.0
3,NaN,VIA BARACCHINI FLAVIO N. 9 (z.d. 1),VIA,BARACCHINI FLAVIO,9,356.0,1,TRUCCO SEMIPERMANENTE,NaN,NaN
4,NaN,VIA BERGAMO N. 12 (z.d. 4),VIA,BERGAMO,12,3189.0,4,NaN,NaN,50.0
...,...,...,...,...,...,...,...,...,...,...
3906,TIPO B CENTRO DI ABBRONZATURA,VIA CANDOGLIA N. 2 ; (z.d. 9),VIA,CANDOGLIA,2,1518.0,9,NaN,NaN,NaN
3907,TIPO D ESTET.APPAR.ELETTROMECC,VIA NIRONE num.002a; (z.d. 1),VIA,NIRONE,NaN,640.0,1,NaN,NaN,NaN
3907,TIPO C TRATT.ESTETICI DIMAGRIM,VIA NIRONE num.002a; (z.d. 1),VIA,NIRONE,NaN,640.0,1,NaN,NaN,NaN
3907,TIPO B CENTRO DI ABBRONZATURA,VIA NIRONE num.002a; (z.d. 1),VIA,NIRONE,NaN,640.0,1,NaN,NaN,NaN
3908,Truccatore,VIA MADONNINA N. 15 ; (z.d. 1),VIA,MADONNINA,15,134.0,1,NaN,NaN,85.0

In [46]:
# Cambio carattere
df['Tipo esercizio pa'] = df['Tipo esercizio pa'].str.title()
df

,Tipo esercizio pa,Ubicazione,Tipo via,Via,Civico,Codice via,ZD,Prevalente,Superficie altri usi,Superficie lavorativa
0,NaN,LGO DEI GELSOMINI N. 10 (z.d. 6),LGO,DEI GELSOMINI,10,5394.0,6,NaN,NaN,55.0
1,NaN,PZA FIDIA N. 3 (z.d. 9),PZA,FIDIA,3,1144.0,9,CENTRO MASSAGGI RILASSANTI NON ESTETICI,2.0,28.0
2,NaN,VIA ADIGE N. 10 (z.d. 5),VIA,ADIGE,10,4216.0,5,CENTRO BENESSERE,2.0,27.0
3,NaN,VIA BARACCHINI FLAVIO N. 9 (z.d. 1),VIA,BARACCHINI FLAVIO,9,356.0,1,TRUCCO SEMIPERMANENTE,NaN,NaN
4,NaN,VIA BERGAMO N. 12 (z.d. 4),VIA,BERGAMO,12,3189.0,4,NaN,NaN,50.0
...,...,...,...,...,...,...,...,...,...,...
3906,Tipo B Centro Di Abbronzatura,VIA CANDOGLIA N. 2 ; (z.d. 9),VIA,CANDOGLIA,2,1518.0,9,NaN,NaN,NaN
3907,Tipo D Estet.Appar.Elettromecc,VIA NIRONE num.002a; (z.d. 1),VIA,NIRONE,NaN,640.0,1,NaN,NaN,NaN
3907,Tipo C Tratt.Estetici Dimagrim,VIA NIRONE num.002a; (z.d. 1),VIA,NIRONE,NaN,640.0,1,NaN,NaN,NaN
3907,Tipo B Centro Di Abbronzatura,VIA NIRONE num.002a; (z.d. 1),VIA,NIRONE,NaN,640.0,1,NaN,NaN,NaN
3908,Truccatore,VIA MADONNINA N. 15 ; (z.d. 1),VIA,MADONNINA,15,134.0,1,NaN,NaN,85.0

In [ ]:
# Controllo prima se i valori nella colonna 'Ubicazione' sono presenti nelle altre colonne
columns_address = ['Tipo via', 'Via', 'Civico', 'ZD']

pattern = r'(\w+)\s+(.+?)\s+(?:N\.|num\.?)\s*(\d+)(?:\s*;?\s*\(z\.d\.\s*(\d+)\))?.*'

# Applica l'estrazione e crea nuove colonne
df_nuove_colonne = df['Ubicazione'].str.extract(pattern)

# Controlla se i valori nelle altre colonne sono uguali a quelli estratti
for i, col in enumerate(columns_address):
    if df_nuove_colonne[i].notnull().any():
        df[f'check_{col}'] = df_nuove_colonne[i] == df[col]
df

# Stampa le righe con False
# TODO: da rivedere
for col in columns_address:
    false_rows = df[df[f'check_{col}'] == False]
    if not false_rows.empty:
        print(f"Discrepanze trovate nella colonna '{col}':")
        print(false_rows[['Ubicazione', col, f'check_{col}']])

Discrepanze trovate nella colonna 'Tipo via':
                                             Ubicazione Tipo via  \
32                 CSO COMO N. 15 interno club f. conti      NaN
33                                                  CSO     COMO
210                       codvia 4386 num.008; (z.d. 4)      CSO
243             mm1 duomo codvia 9112 num.000; (z.d. 1)      CSO
651                VIA SOLARI ANDREA num.002a; (z.d. 6)      PZA
744   VLE FORLANINI ENRICO con ingr. da p.zza artigi...      VIA
745             VLE FORLANINI ENRICO num.0505; (z.d. 4)      VIA
808           CSO GARIBALDI GIUSEPPE num.051a; (z.d. 1)      VLE
808           CSO GARIBALDI GIUSEPPE num.051a; (z.d. 1)      VLE
1060                VIA TARTINI GIUSEPPE n. 34 (z.d. 9)      VIA
1203                   VLE TEODORICO num.0192; (z.d. 8)      VIA
1633            VIA GIOIA MELCHIORRE num.055a; (z.d. 2)      PZA
1775                  VIA MONTE ROSA num.019e; (z.d. 6)      PZA
2221                       VLE MONZA num.1773; (z.d. 2)      VIA
2223                        VLE MONZA num.353; (z.d. 2)      VIA
2413            PZA OBERDAN GUGLIELMO num.000; (z.d. 3)      VIA
2844  VIA LITTA MODIGNANI ALESSANDRO per rettifica t...      PZA
2844  VIA LITTA MODIGNANI ALESSANDRO per rettifica t...      PZA
2844  VIA LITTA MODIGNANI ALESSANDRO per rettifica t...      PZA
3042            VIA GNOCCHI DON CARLO num.033; (z.d. 7)      VLE
3042            VIA GNOCCHI DON CARLO num.033; (z.d. 7)      VLE
3114                     VLE ROMAGNA num.0562; (z.d. 3)      VIA
3114                     VLE ROMAGNA num.0562; (z.d. 3)      VIA
3114                     VLE ROMAGNA num.0562; (z.d. 3)      VIA
3275                  VIA CHIANCIANO num.0102; (z.d. 9)      VLE
3529  CSO GARIBALDI GIUSEPPE p.t. + seminterrato num...      VIA
3529  CSO GARIBALDI GIUSEPPE p.t. + seminterrato num...      VIA
3534  CSO MAGENTA interno piano rialzato num.083; (z...      VIA
3534  CSO MAGENTA interno piano rialzato num.083; (z...      VIA
3699  VIA PAGANO MARIO piano rialzato num.03739; (z....      CSO
3699  VIA PAGANO MARIO piano rialzato num.03739; (z....      CSO
3818                    VLE SABOTINO num.021a; (z.d. 5)      VIA
3818                    VLE SABOTINO num.021a; (z.d. 5)      VIA

      check_Tipo via
32             False
33             False
210            False
243            False
651            False
744            False
745            False
808            False
808            False
1060           False
1203           False
1633           False
1775           False
2221           False
2223           False
2413           False
2844           False
2844           False
2844           False
3042           False
3042           False
3114           False
3114           False
3114           False
3275           False
3529           False
3529           False
3534           False
3534           False
3699           False
3699           False
3818           False
3818           False
Discrepanze trovate nella colonna 'Via':
                                           Ubicazione                Via  \
32               CSO COMO N. 15 interno club f. conti                NaN
33                                                CSO                 15
210                     codvia 4386 num.008; (z.d. 4)               LODI
243           mm1 duomo codvia 9112 num.000; (z.d. 1)           SEMPIONE
319                   VIA BOVISASCA num.173; (z.d. 9)         FERMIGNANO
...                                               ...                ...
3767              VIA SOLARI ANDREA num.043; (z.d. 6)        LORENTEGGIO
3801  VLE CERTOSA interno palestra num.021a; (z.d. 8)            CERTOSA
3801  VLE CERTOSA interno palestra num.021a; (z.d. 8)            CERTOSA
3818                  VLE SABOTINO num.021a; (z.d. 5)  LAGRANGE GIUSEPPE
3818                  VLE SABOTINO num.021a; (z.d. 5)  LAGRANGE GIUSEPPE

      check_Via
32        False
33        False
210       False
243       False
319       False
...         ...
3767      False
3801      False
3801      False
3818      False
3818      False

[133 rows x 3 columns]
Discrepanze trovate nella colonna 'Civico':
                                Ubicazione Civico  check_Civico
32    CSO COMO N. 15 interno club f. conti    NaN         False
33                                     CSO   1111         False
65             VIA BERGAMO N. 12A (z.d. 4)    12A         False
115             VIA LIVIGNO N. 6A (z.d. 9)     6A         False
137   VIA PALIZZI FILIPPO N. 119F (z.d. 8)   119F         False
...                                    ...    ...           ...
3818       VLE SABOTINO num.021a; (z.d. 5)     13         False
3839           VIA BARI num.011d; (z.d. 6)    NaN         False
3907         VIA NIRONE num.002a; (z.d. 1)    NaN         False
3907         VIA NIRONE num.002a; (z.d. 1)    NaN         False
3907         VIA NIRONE num.002a; (z.d. 1)    NaN         False

[239 rows x 3 columns]
Discrepanze trovate nella colonna 'ZD':
                                             Ubicazione            ZD  \
20    VIA STRAMBIO GAETANO N. 23 estetista in appart...             3
32                 CSO COMO N. 15 interno club f. conti           NaN
33                                                  CSO  ACCONCIATORE
45                 PAS DUOMO N. 2 piano primo; (z.d. 1)             1
65                          VIA BERGAMO N. 12A (z.d. 4)             4
...                                                 ...           ...
3904  VIA SARPI FRA' PAOLO N. 1 con ingr.da v.le mon...             1
3904  VIA SARPI FRA' PAOLO N. 1 con ingr.da v.le mon...             1
3907                      VIA NIRONE num.002a; (z.d. 1)             1
3907                      VIA NIRONE num.002a; (z.d. 1)             1
3907                      VIA NIRONE num.002a; (z.d. 1)             1

      check_ZD
20       False
32       False
33       False
45       False
65       False
...        ...
3904     False
3904     False
3907     False
3907     False
3907     False

[690 rows x 3 columns]

In [48]:
# Rimuovo tutto quello dopo N. nella colonna Ubicazione
df['Ubicazione'] = df['Ubicazione'].str.replace(
    r'\s+(N\.|num\.?)\s*\d+.*', '', regex=True
)

# Rimuovo z.d.
regex_pattern = r'\(z\.d\.\s*\d+\)'
df['Tipo esercizio pa'] = np.where(
    df['Tipo esercizio pa'].astype(str).str.contains(regex_pattern, regex=True),
    np.nan,
    df['Tipo esercizio pa']
)
df

,Tipo esercizio pa,Ubicazione,Tipo via,Via,Civico,Codice via,ZD,Prevalente,Superficie altri usi,Superficie lavorativa,check_Tipo via,check_Via,check_Civico,check_ZD
0,NaN,LGO DEI GELSOMINI,LGO,DEI GELSOMINI,10,5394.0,6,NaN,NaN,55.0,True,True,True,True
1,NaN,PZA FIDIA,PZA,FIDIA,3,1144.0,9,CENTRO MASSAGGI RILASSANTI NON ESTETICI,2.0,28.0,True,True,True,True
2,NaN,VIA ADIGE,VIA,ADIGE,10,4216.0,5,CENTRO BENESSERE,2.0,27.0,True,True,True,True
3,NaN,VIA BARACCHINI FLAVIO,VIA,BARACCHINI FLAVIO,9,356.0,1,TRUCCO SEMIPERMANENTE,NaN,NaN,True,True,True,True
4,NaN,VIA BERGAMO,VIA,BERGAMO,12,3189.0,4,NaN,NaN,50.0,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3906,Tipo B Centro Di Abbronzatura,VIA CANDOGLIA,VIA,CANDOGLIA,2,1518.0,9,NaN,NaN,NaN,True,True,True,True
3907,Tipo D Estet.Appar.Elettromecc,VIA NIRONE,VIA,NIRONE,NaN,640.0,1,NaN,NaN,NaN,True,True,False,False
3907,Tipo C Tratt.Estetici Dimagrim,VIA NIRONE,VIA,NIRONE,NaN,640.0,1,NaN,NaN,NaN,True,True,False,False
3907,Tipo B Centro Di Abbronzatura,VIA NIRONE,VIA,NIRONE,NaN,640.0,1,NaN,NaN,NaN,True,True,False,False
3908,Truccatore,VIA MADONNINA,VIA,MADONNINA,15,134.0,1,NaN,NaN,85.0,True,True,True,True